### ISSUE TITLE
What's the use of the dictionary folder ?

### ISSUE THREAD

**Issue by appledora** [dsindex/ntagger#13]
Hello there's a `dicitonary` folder in the repo. I have tried searching for it's usage in the documentation but couldn't find anything meaningful, which could be a mistake on my part. I am assuming that perhaps it is eventually used for lexicon/gazetteer based token classification tasks. It would be really helpful if you could tell me how the repo is utilizing this asset. Thanks.

**Comment by dsindex** [comment]
the dictionary folder is not used in repo right now. i am sorry for that;

very long time ago, i was trying to implement Context-Aware Dictionary Knowledge Network described in the paper :

Named Entity Recognition with Context-Aware Dictionary Knowledge
https://aclanthology.org/2020.ccl-1.85.pdf

![13CE065D-2335-4F9F-8B68-6D55E873BC6F](https://user-images.githubusercontent.com/8259057/168094036-6413e87b-8a32-4550-a49d-efd5fe0893a2.jpeg)

![5B30B3A3-ED52-4F72-98C9-16FA4ABEDFFD](https://user-images.githubusercontent.com/8259057/168094065-57f081dc-f62b-4ce2-92bc-8ad873893b00.jpeg)

but i had no time to implement yet.

**Comment by appledora** [comment]
Thanks a lot for taking the time! This is a fantastic repo, regardless. Looking forward to new improvements!
