### ISSUE TITLE
NER Inferencing 

### ISSUE THREAD

**Issue by geo47** [dsindex/ntagger#9]
Hi @dsindex 

By any chance, are you going to implement the inferencing for NER from the trained model. Also, have you tried KoBERT for Korean NER task?

**Comment by dsindex** [comment]
well~ inference codes are a little bit complicated. but, i will add it in the near future.

and... you can refer `NER task using KoBERT` to https://github.com/eagle705/pytorch-bert-crf-ner/blob/master/train_bert_crf.py#L91

**Comment by geo47** [comment]
Thanks very informative.
Looking forward for the inference part :-)

Thanks

**Comment by appledora** [comment]
@dsindex any updates on the inference codes?
